name: CI/CD Deploy to VPS using Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # (tuỳ chọn) bỏ các file không cần đưa lên VPS để context build gọn hơn
      - name: Prune context
        run: |
          rm -rf .git .github .idea target || true

      - name: Clean old source code on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: 22
          script: |
            set -e
            sudo mkdir -p /opt/keys/firebase
            sudo mkdir -p "${{ vars.TARGET_DIR }}"
            # Ghi secret FIREBASE_SA_B64 thành file JSON (an toàn, không lưu trong repo)
            echo "${{ secrets.FIREBASE_SA_B64 }}" | base64 -d | sudo tee /opt/keys/firebase/serviceAccount.json >/dev/null
            sudo chmod 600 /opt/keys/firebase/serviceAccount.json

      - name: Copy source code to VPS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: 22
          source: "."
          target: "${{ vars.TARGET_DIR }}"
          overwrite: true
          timeout: 2m
          command_timeout: 10m

      - name: SSH into VPS and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: 22
          script: |
            set -e
            APP_DIR="${{ vars.TARGET_DIR }}"
            SERVICE="${{ vars.SERVICE_NAME }}"
            cd "$APP_DIR"

            chmod 644 /opt/keys/firebase/serviceAccount.json

            # Dừng & xoá container cũ (nếu có)
            docker stop "$SERVICE" 2>/dev/null || true
            docker rm "$SERVICE" 2>/dev/null || true

            # Build image (tag theo SERVICE)
            docker build -t "$SERVICE" .

            # Chạy container, mount serviceAccount.json vào container ở /run/secrets/firebase_sa.json
            docker run -d --name "$SERVICE" \
              -p 2170:8080 \
              -v /opt/keys/firebase/serviceAccount.json:/run/secrets/firebase_sa.json:ro \
              -e GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase_sa.json \
              "$SERVICE"

            # Kiểm tra log khởi động nhanh
            sleep 3
            docker logs --tail=100 "$SERVICE" || true
